version: '3.9'

services:
  post:
    build:
      context: .
      dockerfile: ./apps/post/Dockerfile
      target: development
    command: npm run start:dev post
    env_file:
      - ./apps/post/.env
    ports:
      - '3000:3000'
    networks:
      newspaper_net:
        ipv4_address: 192.168.0.6
    volumes:
      - .:/usr/src/app
    restart: always
  category:
    build:
      context: .
      dockerfile: ./apps/category/Dockerfile
      target: development
    command: npm run start:dev category
    env_file:
      - ./apps/category/.env
    ports:
      - '3004:3004'
    networks:
      newspaper_net:
        ipv4_address: 192.168.0.7
    volumes:
      - .:/usr/src/app
    restart: always
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    networks:
      newspaper_net:
        ipv4_address: 192.168.0.5
    volumes:
      - .:/usr/src/app
    restart: always

  generalsetting:
    build:
      context: .
      dockerfile: ./apps/generalsetting/Dockerfile
      target: development
    command: npm run start:dev generalsetting
    env_file:
      - ./apps/generalsetting/.env
    ports:
      - '3003:3003'
    networks:
      newspaper_net:
        ipv4_address: 192.168.0.4
    volumes:
      - .:/usr/src/app
    restart: always

  postgres:
    image: postgres:16.0-alpine3.18
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=newspaper
    ports:
      - "5432:5432"
    networks:
      newspaper_net:
        ipv4_address: 192.168.0.2 

  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    networks:
      newspaper_net:
        ipv4_address: 192.168.0.3

networks:
  newspaper_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.1